# Generated by Django 3.0 on 2023-04-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_auto_20230401_1828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employeee',
        ),
    ]
