# Generated by Django 3.0 on 2023-04-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
    ]
