# Generated by Django 3.0 on 2023-04-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_jobdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compnyNAme', models.CharField(max_length=20)),
                ('jobName', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('Time', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='jobDetails',
        ),
    ]
