# Generated by Django 3.0 on 2023-07-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeelogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
